name: MacOS

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build/

jobs:
  build:
    name: Deploy on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install deps
      run: |
        brew update
        brew install curl

    - name: Configure VKAPI Library CMake
      run: cmake -B ${{ env.CMAKE_BUILD_DIR }} -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build VKAPI Library
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --config ${{ env.BUILD_TYPE }}
      
    - name: Install VKAPI Library
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --target install --config ${{ env.BUILD_TYPE }}

    # Configure, Build and Install WE - With Examples
    - name: Configure VKAPI Library CMake WE
      run: cmake -B ${{ env.CMAKE_BUILD_DIR }} -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build VKAPI Library WE
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --config ${{ env.BUILD_TYPE }}
      
    - name: Install VKAPI Library WE
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --target install --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ env.CMAKE_BUILD_DIR }}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{ env.BUILD_TYPE }}
      
      
