name: Ubuntu

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt upgrade && sudo apt install curl && sudo apt-get install libcurl4-openssl-dev

    - name: Configure VKAPI Library CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build VKAPI Library
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install VKAPI Library
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}

    # Configure, Build and Install WE - With Examples
    - name: Configure VKAPI Library CMake WE
      run: cmake -B ${{github.workspace}}/build -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build VKAPI Library WE
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install VKAPI Library WE
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
